# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

image:
  repository: ghcr.io/agntcy/oasf-server
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort

volumes:
  - name: schema
    hostPath:
      path: /schema
      type: Directory

volumeMounts:
  - name: schema
    mountPath: /schema

env:
  SCHEMA_DIR: /schema
